"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

// Define the shape of a Trip Log
type TripLog = {
  id: number;
  created_at: string;
  user_id: string; 
  vehicle_id: string;
  odometer: number;
  trip_type: string;
  notes: string;
  driver_name?: string; 
};

// Define User Profile shape
type UserProfile = {
  id: string;
  firstName: string;
  lastName: string;
  role: string;
  email: string;
};

export default function Dashboard() {
  const router = useRouter();
  const [supabase] = useState(() => createClient());
  
  // State for Tabs
  const [activeTab, setActiveTab] = useState<'new' | 'history' | 'all'>('new');
  
  // State for Data
  const [logs, setLogs] = useState<TripLog[]>([]);
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);

  // --- EXPORT HELPERS ---

  // 1. Download as CSV (Excel/Google Sheets)
  const downloadCSV = (log: TripLog) => {
    const headers = ['Log ID', 'Date', 'Time', 'Driver', 'Trip Type', 'Vehicle ID', 'Odometer', 'Notes'];
    const dateObj = new Date(log.created_at);
    
    // Create CSV Row safely handling commas and quotes
    const row = [
      log.id,
      dateObj.toLocaleDateString(),
      dateObj.toLocaleTimeString(),
      `"${log.driver_name || 'Unknown'}"`,
      log.trip_type,
      log.vehicle_id,
      log.odometer,
      `"${(log.notes || '').replace(/"/g, '""')}"` // Escape quotes in notes
    ];

    const csvContent = [headers.join(','), row.join(',')].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    // Trigger Download
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `trip_log_${log.id}_${log.driver_name?.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // 2. Print to PDF (Opens Print Dialog)
  const printLog = (log: TripLog) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return alert("Please allow popups to print logs.");

    const html = `
      <html>
        <head>
          <title>Trip Log #${log.id}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #333; }
            h1 { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
            .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
            .meta { color: #666; font-size: 0.9em; }
            .grid { display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin-bottom: 30px; }
            .label { font-weight: bold; color: #444; }
            .notes-box { border: 1px solid #ddd; background: #f9f9f9; padding: 15px; border-radius: 4px; }
            .footer { margin-top: 50px; font-size: 0.8em; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
          </style>
        </head>
        <body>
          <h1>${log.trip_type} Report</h1>
          
          <div class="header">
            <div><strong>Driver:</strong> ${log.driver_name || 'Unknown'}</div>
            <div class="meta">
              <strong>Log ID:</strong> #${log.id} <br/>
              ${new Date(log.created_at).toLocaleString()}
            </div>
          </div>

          <div class="grid">
            <div class="label">Vehicle ID:</div>
            <div>${log.vehicle_id}</div>

            <div class="label">Odometer:</div>
            <div>${log.odometer}</div>

            <div class="label">Trip Type:</div>
            <div>${log.trip_type}</div>
          </div>

          <div class="notes-box">
            <div class="label" style="margin-bottom: 5px;">Notes / Issues:</div>
            <p style="margin: 0; white-space: pre-wrap;">${log.notes || "No notes provided."}</p>
          </div>

          <div class="footer">
            Generated by Symbria Delivery Logistics System
          </div>

          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
  };

  // --- DATA LOADING ---
  const fetchData = useCallback(async () => {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        router.replace('/login');
        return;
      }

      const { user } = session;
      const metadata = user.user_metadata || {};

      setUserProfile({
        id: user.id,
        email: user.email || "",
        firstName: metadata.first_name || "",
        lastName: metadata.last_name || "",
        role: metadata.role || "Driver",
      });

      const { data, error } = await supabase
        .from('trip_logs')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setLogs(data || []);
    } catch (error) {
      console.error("Error loading dashboard:", error);
    } finally {
      setLoading(false);
    }
  }, [supabase, router]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!userProfile) return;

    const formData = new FormData(e.currentTarget);
    const newLog = {
      vehicle_id: formData.get('vehicle_id'),
      odometer: formData.get('odometer'),
      trip_type: formData.get('trip_type'),
      notes: formData.get('notes'),
      driver_name: `${userProfile.firstName} ${userProfile.lastName}`
    };

    const { error } = await supabase.from('trip_logs').insert(newLog);

    if (error) {
      alert("Error submitting log: " + error.message);
    } else {
      alert("Success! Log submitted.");
      e.currentTarget.reset(); 
      fetchData(); 
      setActiveTab('history'); 
    }
  }

  const visibleLogs = activeTab === 'history' 
    ? logs.filter(log => log.user_id === userProfile?.id) 
    : logs;

  if (loading) {
    return <div className="p-8 text-center text-gray-500">Loading your data...</div>;
  }

  return (
    <div className="p-4 md:p-8 max-w-6xl mx-auto">
      
      {/* HEADER */}
      <header className="mb-8 flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">Dashboard</h1>
          <p className="text-gray-500 text-sm mt-1">Welcome back, {userProfile?.firstName}</p>
        </div>
        
        {userProfile && (
          <h3 className="text-gray-400 text-right font-medium">
            {userProfile.firstName} {userProfile.lastName} <br />
            <span className={`uppercase text-xs tracking-wider border px-2 py-0.5 rounded-full mt-1 inline-block ${
              userProfile.role === 'Management' ? 'border-purple-300 text-purple-600 bg-purple-50' : 'border-gray-300'
            }`}>
              {userProfile.role}
            </span>
          </h3>
        )}
      </header>

      {/* TABS */}
      <div className="flex border-b border-gray-300 mb-6 overflow-x-auto">
        <button
          onClick={() => setActiveTab('new')}
          className={`px-6 py-3 font-medium transition-colors whitespace-nowrap ${
            activeTab === 'new' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          New Pre/Post Trip Form
        </button>
        <button
          onClick={() => setActiveTab('history')}
          className={`px-6 py-3 font-medium transition-colors whitespace-nowrap ${
            activeTab === 'history' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          My Submitted Logs
        </button>
        {userProfile?.role === 'Management' && (
          <button
            onClick={() => setActiveTab('all')}
            className={`px-6 py-3 font-medium transition-colors whitespace-nowrap ${
              activeTab === 'all' ? 'border-b-2 border-purple-600 text-purple-600' : 'text-gray-500 hover:text-purple-600'
            }`}
          >
            All Driver Logs (Admin)
          </button>
        )}
      </div>

      {/* NEW FORM */}
      {activeTab === 'new' && (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 max-w-3xl">
          <h2 className="text-xl font-semibold mb-4">Submit New Log</h2>
          <form onSubmit={handleSubmit} className="flex flex-col gap-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <label className="flex flex-col gap-1">
                <span className="text-sm font-semibold text-gray-700">Trip Type</span>
                <select name="trip_type" className="border p-3 rounded-lg bg-white" required>
                  <option value="Pre-Trip">Pre-Trip Inspection</option>
                  <option value="Post-Trip">Post-Trip Inspection</option>
                </select>
              </label>
              <label className="flex flex-col gap-1">
                <span className="text-sm font-semibold text-gray-700">Vehicle ID</span>
                <input name="vehicle_id" type="text" placeholder="Ex: Van-104" className="border p-3 rounded-lg" required />
              </label>
            </div>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-semibold text-gray-700">Current Odometer</span>
              <input name="odometer" type="number" placeholder="000000" className="border p-3 rounded-lg" required />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-semibold text-gray-700">Notes / Issues</span>
              <textarea name="notes" placeholder="Any damage, maintenance needs, or comments..." className="border p-3 rounded-lg" rows={3} />
            </label>
            <button type="submit" className="bg-green-600 text-white font-bold py-3 px-6 rounded-lg hover:bg-green-700 transition self-start">
              Submit Log
            </button>
          </form>
        </div>
      )}

      {/* LIST VIEWS */}
      {(activeTab === 'history' || activeTab === 'all') && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          {visibleLogs.length === 0 ? (
            <div className="p-8 text-center text-gray-500">No logs found.</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    {/* Only Show Actions Column on Admin Tab */}
                    {activeTab === 'all' && <th className="p-4 font-semibold text-gray-700 bg-purple-50">Actions</th>}
                    {activeTab === 'all' && <th className="p-4 font-semibold text-gray-700">Driver</th>}
                    <th className="p-4 font-semibold text-gray-700">Date</th>
                    <th className="p-4 font-semibold text-gray-700">Type</th>
                    <th className="p-4 font-semibold text-gray-700">Vehicle</th>
                    <th className="p-4 font-semibold text-gray-700">Odometer</th>
                    <th className="p-4 font-semibold text-gray-700">Notes</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {visibleLogs.map((log) => (
                    <tr key={log.id} className="hover:bg-gray-50 transition">
                      
                      {/* ACTION BUTTONS (Admin Only) */}
                      {activeTab === 'all' && (
                        <td className="p-4 bg-purple-50/30">
                          <div className="flex gap-2">
                            <button 
                              onClick={() => printLog(log)}
                              className="text-xs bg-gray-200 hover:bg-gray-300 text-gray-700 px-2 py-1 rounded transition"
                              title="Print to PDF"
                            >
                              📄 PDF
                            </button>
                            <button 
                              onClick={() => downloadCSV(log)}
                              className="text-xs bg-green-100 hover:bg-green-200 text-green-700 px-2 py-1 rounded transition"
                              title="Download for Excel/Sheets"
                            >
                              📊 CSV
                            </button>
                          </div>
                        </td>
                      )}

                      {activeTab === 'all' && (
                        <td className="p-4 font-medium text-gray-900">
                          {log.driver_name || "Unknown"}
                        </td>
                      )}

                      <td className="p-4 text-gray-600">
                        {new Date(log.created_at).toLocaleDateString()} <br/>
                        <span className="text-xs text-gray-400">
                          {new Date(log.created_at).toLocaleTimeString()}
                        </span>
                      </td>
                      <td className="p-4">
                        <span className={`px-2 py-1 rounded text-xs font-bold ${
                          log.trip_type === 'Pre-Trip' ? 'bg-blue-100 text-blue-700' : 'bg-orange-100 text-orange-700'
                        }`}>
                          {log.trip_type}
                        </span>
                      </td>
                      <td className="p-4 font-medium text-gray-800">{log.vehicle_id}</td>
                      <td className="p-4 text-gray-600">{log.odometer}</td>
                      <td className="p-4 text-gray-500 max-w-xs truncate">{log.notes || "-"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
